FROM ghcr.io/cross-rs/zig:main

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y pkg-config libdbus-1-dev:arm64 libssl-dev:arm64

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
