FROM ghcr.io/cross-rs/zig:main

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y pkg-config libdbus-1-dev:armhf libssl-dev:armhf

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
